version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        ports:
            - "5500:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

  locust:
    build:
      context: .
      dockerfile: Dockerfile-locust
    ports:
      - "8089:8089"